# Generated by Django 5.0.3 on 2024-03-31 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="The user controlling this package from admin panel.\nThis will automatically be set as you",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Package Manager",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipment_origin",
                to="app.location",
                verbose_name="Origin(From)",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="app.shipment",
                verbose_name="Package",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="app.shipment",
                verbose_name="Package Item",
            ),
        ),
        migrations.AddField(
            model_name="tracking",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g. Warehouse, Airport etc.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.location",
                verbose_name="Current Location",
            ),
        ),
        migrations.AddField(
            model_name="tracking",
            name="logistics_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.logisticcompany",
                verbose_name="Logistic Company",
            ),
        ),
        migrations.AddField(
            model_name="tracking",
            name="shipment",
            field=models.ForeignKey(
                help_text="The package being tracked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_log",
                to="app.shipment",
                verbose_name="Package",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shipment",
            unique_together={("tracking_number", "origin", "destination")},
        ),
        migrations.AlterUniqueTogether(
            name="tracking",
            unique_together={("shipment", "location", "status")},
        ),
    ]
