# Generated by Django 5.0.3 on 2024-03-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="name",
        ),
        migrations.AlterField(
            model_name="shipment",
            name="total_est",
            field=models.FloatField(help_text="Total estimated cost of the shipment"),
        ),
    ]
