# Generated by Django 5.0.3 on 2024-03-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_location_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "Preparing"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                    ("delayed", "Delayed"),
                    ("on_hold", "On Hold"),
                ],
                default="preparing",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="total_est",
            field=models.FloatField(
                help_text="Total estimated cost of the shipment(eg. 100.50)"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="total_weight",
            field=models.FloatField(
                help_text="Total weight of the shipment in KGs(eg. 10.5)"
            ),
        ),
    ]
