# Generated by Django 5.0.3 on 2024-03-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_tracking_status_alter_shipment_total_est_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tracking",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "Preparing"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("returned", "Returned"),
                    ("delayed", "Delayed"),
                    ("on_hold", "On Hold"),
                ],
                default="preparing",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "Preparing"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("returned", "Returned"),
                    ("delayed", "Delayed"),
                    ("on_hold", "On Hold"),
                ],
                default="preparing",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tracking",
            unique_together={("shipment", "location", "status")},
        ),
    ]
