# Generated by Django 5.0.3 on 2024-03-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_tracking_unique_together_alter_shipment_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="status",
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="destination",
            field=models.ForeignKey(
                help_text="The destination of the package/receiver's address",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipment_destination",
                to="app.location",
                verbose_name="Destination(To)",
            ),
        ),
    ]
