# Generated by Django 5.0.3 on 2024-03-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_shipment_status_shipment_receiver_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="item",
        ),
        migrations.AddField(
            model_name="image",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="app.shipment",
                verbose_name="Package Item",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(
                help_text="Get the latitude and longitude from Google Maps - gps-coordinates.net"
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="app.shipment",
                        verbose_name="Package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
